all: assignment3.c
	sudo gcc -Wall -o assignment3 assignment3.c DEV_Config.c PCA9685.c -lm -lwiringPi

assignment3: assignment3.c
	sudo gcc -Wall -o assignment3 assignment3.c DEV_Config.c PCA9685.c -lm -lwiringPi

clean:
	sudo rm assignment3

run:
	sudo gcc -Wall -o assignment3 assignment3.c DEV_Config.c PCA9685.c -lm -lwiringPi
	sudo ./assignment3

